version: "3.3"
services:
 postgres:
  image: postgres:12-alpine
  container_name: xy_postgres
  restart: always
  environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
  ports:
    - 5432:5432
  volumes:
    - ./data:/var/lib/postgresql/data

