version: "3.7"
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - LANG=C.UTF-8
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf
